### PR TITLE
Switch to bitly OAuth

### PR DESCRIPTION
**Pull request by contactashish13**
#244

### CODE REVIEW

**Comment by UVLabs** [comment]
@contactashish13 what's the update process for this? I tried updating on a site where bit.ly was already setup, then I saw the posts were shared with the full link (as they should in cases where something is wrong with the shortner)

But when I tried to remove the old credentials or something I do not get the text area for the general access token. I tried switching to a new shortener and then switching back to bit.ly but it still shows the old text fields and no the general access token text screen.

-----

On fresh installs of the plugin it shows correct with the general access token text field.

**Comment by contactashish13** [comment]
@UVLabs should be okay now with the latest commit.

**Comment by UVLabs** [comment]
@contactashish13 was this supposed to continue using the old credentials unless a user updated? If so then it did show the new input box now after updating but the links are no longer shortened, A user would have to go put in the new Oauth key

**Comment by contactashish13** [comment]
@UVLabs unfortunately, that is how it will behave as there is no alternative. Once the user upgrades and if they are using bit.ly then they should be shown a notice that says that they will have to add the access token.

**Comment by selul** [comment]
@contactashish13 this is not really ok, plugin and this feature is widely used and is not a solution to broke them. 
If it possible to make a legacy compatibility where if when sharing with bitly, if the old credentials are present switch the shortening logic using the old one, otherwise use the one.
On the frontend part, it doesn't matter that much if we show directly the new field.

**Comment by contactashish13** [comment]
@UVLabs I've implemented Marius' suggestion in the latest commit. can you please test?

**Comment by UVLabs** [comment]
@contactashish13 old install with old credentials updated with new plugin still leaves link unshortened

**Comment by contactashish13** [comment]
@UVLabs should be okay now.

**Pull request merged**
