### PR TITLE
Fixes character issue for hashtags from tags and categories

### PR DESCRIPTION
**Pull request by UVLabs**

### CODE REVIEW

**Comment by selul** [comment]
@UVLabs something crossed my mind, does twitter support such chars in hashtags ?

**Comment by selul** [comment]
@UVLabs you might want to use `sanitize_title_with_dashes` instead of replacing just whitespaces, which is too weak.

**Comment by UVLabs** [comment]
@selul, yes twitter supports it, I tested it out, I don't think that function would be a food idea because someone might have a tag/category, for example, *Starbucks Coffee* and with the way I did it then it would make the hashtag #StarbucksCoffee 

I'm thinking about how people use hashtags in general #StarbucksCoffee is way more normal than #Starbucks-Coffee

Another example is *Home Improvement* from a hashtag discovery standpoint I think a user would prefer if their hashtag would show up as #HomeImprovement instead of #Home-Improvement, hashtags rarely have dashes in them

**Comment by selul** [comment]
@UVLabs the thing with that function is that covers a wider range of chars when normalizing the string, i.e symbols, non-printable chars, etc. 

What do you think of this idea -> apply `sanitize_title_with_dashes` over that text and then `str_replace('-','',)` Basically replace the dashes with empty char?

**Comment by UVLabs** [comment]
Ok thats a good idea, i'll see how it works with special chars thanks

**Comment by UVLabs** [comment]
I think something went wrong on travis' end

**Comment by selul** [comment]
@UVLabs what do you think of using directly the twitter regex for parsing the hashtag -> https://github.com/twitter/twitter-text/blob/master/js/src/regexp/validHashtag.js

We can implement this into the clean method you have build.

**Comment by UVLabs** [comment]
@contactashish13 can you check out this pull request and see if there's any issue? This is the issue we're fixing: https://github.com/Codeinwp/tweet-old-post/issues/171

I created a simple method just to handle any troublesome characters in taxonomy names and custom fields for the hashtag functionality.

https://github.com/Codeinwp/tweet-old-post/pull/189/commits/2ed73f8f24df11a91c253f0583c36384ba4358b8#diff-3773c5414362ee34b888568b82c4ba43R335

**Comment by selul** [comment]
@UVLabs here you forgot to add this to @contactashish13 project.

**Comment by contactashish13** [comment]
@UVLabs @selul I see that that issue has been closed and the PR has been merged, so is this still relevant?

**Pull request merged**
