### PR TITLE
Release

### PR DESCRIPTION
**Pull request by vytisbulkevicius**
- Fixed post-sharing issue with post image
- Added Twitter v2 API support

### CODE REVIEW

**Comment by vytisbulkevicius** [comment]
Hey @girishpanchal30, please resolve this conflict. Thanks!

**Comment by girishpanchal30** [comment]
@vytisbulkevicius, Please merge this PR https://github.com/Codeinwp/tweet-old-post/pull/876 into development to fix file conflicts.

**Comment by vytisbulkevicius** [comment]
@girishpanchal30, PR merged but I still see the conflict here

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Resolved, seems the build zip CI action failed due to a PHP version issue with composer packages.
I've already changed PHP version here: https://github.com/Codeinwp/tweet-old-post/pull/875/commits/836b95818cacf8b84a55fd4e17c03e821cbd281a

**Comment by vytisbulkevicius** [comment]
@girishpanchal30 thank you. As for the build itself seems like it's failing now and requires composer update:

> Error: Your lock file does not contain a compatible set of packages. Please run composer update.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Fixed, Sorry for confusion :pray:

**Pull request merged**
