### PR TITLE
Move the tracking setting to the general setting tab

### PR DESCRIPTION
**Pull request by girishpanchal30**
I've moved the data tracking `Global Settings` field to the `General Settings` tab.

Close https://github.com/Codeinwp/tweet-old-post-pro/issues/512

### CODE REVIEW

**Review by Soare-Robert-Daniel — CHANGES_REQUESTED** [review]
I see that you removed the `toggle_tracking` function, and I do not know if you updated the option to enable/disable the tracking script 🤔 . Is there an equivalent of `update_option( 'tweet_old_post_logger_flag', $tracking ? 'yes' : 'no' );` ?

If you are now integrating the value into dashboard flow, there should be some toggle for the tracking option linked to it when you save the values.

**Comment by girishpanchal30** [comment]
@Soare-Robert-Daniel

> I see that you removed the toggle_tracking function, and I do not know if you updated the option to enable/disable the tracking script

The `toggle_tracking` function is used to save the `enable/disable` on the change event and now it will be saved when the user clicks on the save button so I've removed it.


> Is there an equivalent of update_option( 'tweet_old_post_logger_flag', $tracking ? 'yes' : 'no' ); ?

Previously it was used here https://github.com/Codeinwp/tweet-old-post/blob/a54109cb8e6e2fda708ee560349946232ace4222/includes/admin/class-rop-admin.php#L390
 when localized the settings data, I used it here when the `tracking` key was not found in general settings.

**Comment by Soare-Robert-Daniel** [comment]
@girishpanchal30, I see what was your point. 

Here is the missing context: the option `'tweet_old_post_logger_flag'` controls the actual loading of the script from Themeisle SDK https://github.com/Codeinwp/themeisle-sdk/blob/b9ba5697b150eddacb4aa482b363d9f459f822c5/src/Modules/Logger.php#L117

You moved the value inside the `rop_data`, but the SDK does not use it.

You also have to update that option when you save the dashboard to actually make it work. 

To test whether the script was loaded, check in the browser console if `window.tiTrk` and `window.tiTelemetry` are available (make sure to not have other products with tracking enabled)

**Comment by girishpanchal30** [comment]
@Soare-Robert-Daniel Thank you for sharing the actual way to make it work properly.

Now I've also updated the `tweet_old_post_logger_flag` option when saving the dashboard settings, I tested it with the browser console and it seems working fine.

Thanks

**Comment by rodica-andronache** [comment]
@girishpanchal30 tested and it works well 👍

**Review by Soare-Robert-Daniel — APPROVED** [review]

**Pull request merged**
