### PR TITLE
Add X limit handling and Logs Export button

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
## Summary

Changelog:

- Add conditions to respect the X limit. Once the limit is reached, we will display a log of the limits and their reset time. Until the limit is reset, now sharing will be done.
- Add a button that exports the logs as a txt file and update the structure display to reflect the content from the file. This should help the support team.
- Added the param `plugin_version` for Twitter/X sign URL to pass the authorization process.
- Added new log messages to encourage the user to use his own API keys.
- When the user shares the post via our app, the sharing will done by the server. The plugin will send an authorization token and the post data to our endpoint.
- `Sharing As Image Post` will be available only for users who use their API key. The logic for uploading the images to X/Twitter will not be ported to the server. We should update [this article](https://docs.revive.social/article/958-how-to-share-posts-as-image-posts-to-social-accounts) to include the information

> [!NOTE]  
> Make sure to read https://github.com/Codeinwp/rop-auth-service/pull/78 to get the full picture of the change.

#### Before
image (1)

#### After
image

image

image

## Testing

Things to look for:
- `Sharing As Image Post` will be available only for users who use their API key (`Use My Own Keys`)
- Make sure the X/Twitter post sharing is working when for both options of using your own API key OR signing in with our app.
- If you use the `Sign In` option, you should not have any official X/Twitter credentials registered by the plugin in your account profile. You can check this by inspecting the network request, as in the image below. **You should have only the `rop_auth_token`, but if you use the option `Use My Own Keys`, then you should see values with the prefix `oauth_` instead of `rop_auth_token`**
Screenshot 2024-01-15 at 17 32 30

> [!CAUTION]
> If you find an issue regarding the authentication values, please send the values in private.

Another thing to test: use the current version of RoP from WP.org, introduce your Twitter API via Sign In, then switch to the build from this PR. With this procedure, you will be connect to the current version of server (not the new one mentioned in above descriptions). 

Try to share a post, you will receive an error about time limit reached, when you try again, you will get a message about when the time limit reset:

image

### CODE REVIEW

**Review by preda-bogdan — APPROVED** [review]

**Review by GrigoreMihai — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and here is what i found:

- [ ] Should we change the button to **X (Twitter)** and have better alignment as @mghenciu said [here](https://github.com/Codeinwp/themeisle/issues/1605#issuecomment-1875198505) -> https://vertis.d.pr/i/ciM3gI
- [ ] We should change the words here to uppercase API https://vertis.d.pr/i/Qjg8Pc
- [ ] I managed to share multiple posts using a free account and no API keys https://vertis.d.pr/i/C5LYQ9. I think because I already had some API keys generated, they got automatically linked in ROP, because this name **1704849955729629185IrinelOld** (the application name set in twitter developer settings) appeared when i had to authorize the access.
- [ ] After adding my website URL in the [twitter developer settings](https://vertis.d.pr/i/d56CKK), when i try to connect the account (without API keys), i'm getting redirected to a different URL https://vertis.d.pr/i/sZw5gZ -> https://crimson-sound-ioadxd7to4ji.ymirsites.com/tw_auth?callback_url=https%3A%2F%2Frop-x-update.s3-tastewp.com%2Fwp-admin%2Fadmin.php%3Fpage%3DTweetOldPost&token=da4ac6fdfe7b32e3b22a7bd17e317062b39e2865&signature=aae3bf0bab064c89d5d944ca8df727c7&data=aXJpbmVsQHRoZW1laXNsZS5jb20%3D&plugin_version=9.0.21 (I think they got mixed because multiple websites are tied to the same twitter account)
- [ ] If i add the **wrong API keys**, i'm also getting a warning https://vertis.d.pr/i/B4XQTL
- [ ] I didn't manage to connect the account with the **Authentication tokens** or **OAuth 2.0 Client ID and Client Secret**. It only connected with the **Consumer Keys** but the account appeared as inactive https://vertis.d.pr/v/arCJ7H

You can check on my instance:
```
 Admin area URL: https://rop-x-update.s3-tastewp.com/wp-admin 
 Username: irinel 
 Password: zlWFV9umnX4 
```

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  I managed to share multiple posts using a free account and no API keys https://vertis.d.pr/i/C5LYQ9. I think because I already had some API keys generated, they got automatically linked in ROP, because this name **1704849955729629185IrinelOld** (the application name set in twitter developer settings) appeared when i had to authorize the access.

Because the app was created with the testing account.

> * [ ]  After adding my website URL in the [twitter developer settings](https://vertis.d.pr/i/d56CKK), when i try to connect the account (without API keys), i'm getting redirected to a different URL https://vertis.d.pr/i/sZw5gZ -> https://crimson-sound-ioadxd7to4ji.ymirsites.com/tw_auth?callback_url=https%3A%2F%2Frop-x-update.s3-tastewp.com%2Fwp-admin%2Fadmin.php%3Fpage%3DTweetOldPost&token=da4ac6fdfe7b32e3b22a7bd17e317062b39e2865&signature=aae3bf0bab064c89d5d944ca8df727c7&data=aXJpbmVsQHRoZW1laXNsZS5jb20%3D&plugin_version=9.0.21 (I think they got mixed because multiple websites are tied to the same twitter account)

Since the stagging website used the same credentials from the testing account, when you regenerated the API keys, the one from stagging became obsolete. 


> * [x]  If i add the **wrong API keys**, i'm also getting a warning https://vertis.d.pr/i/B4XQTL
> * [ ]  I didn't manage to connect the account with the **Authentication tokens** or **OAuth 2.0 Client ID and Client Secret**. It only connected with the **Consumer Keys** but the account appeared as inactive https://vertis.d.pr/v/arCJ7H

To my knowledge, we do not support those. Only the Consumer Keys.

Also, the reason you saw the error about services was pretty tricky to debug.

When you remove via a single action (the delete option that appears when making the account inactive), we do not remove all the data tied to that account. A function did not have a proper checking for it and gave the error.

Regarding the inactive state, I see that in the code it is done on purpose here: 
https://github.com/Codeinwp/tweet-old-post/blob/1b67a0b7c49b50d1a14be315c21c9033821a8681/includes/admin/services/class-rop-twitter-service.php#L311-L313

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, now it should work.

Also, I updated the staging server to use the same credentials as the normal app.

If you try to post with the `Sign In`, you will now get the quota limit from the real app.

You will get something like this:

image

ℹ️ If you test it when the quota reset, you might not see it.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Checked again and everything's fine now 🚀

**Pull request merged**
