### PR TITLE
pinterest sharing #101

### PR DESCRIPTION
**Pull request by contactashish13**

### CODE REVIEW

**Comment by contactashish13** [comment]
@selul this is failing once again. Can you please take a look?

**Comment by selul** [comment]
@contactashish13 you have two tests failing, is not related to that issue.

**Comment by contactashish13** [comment]
@selul my changes do not affect the license. I don't think this is related to my changes. 

image

**Comment by selul** [comment]
@contactashish13 what about this -> https://github.com/Codeinwp/tweet-old-post/pull/203/files#diff-73289f7ac574d1561cc23311bea24cf1R340

**Comment by contactashish13** [comment]
@selul oops! That should never have gone in :slightly_frowning_face: . Thanks! :)

**Comment by selul** [comment]
@contactashish13 hehe, no problem. I'm happy that we got it sorted.

**Comment by UVLabs** [comment]
@contactashish13 we got some merge conflicts here after I merged your rebrandly pull, also got here as well: https://github.com/Codeinwp/tweet-old-post/pull/203

**Comment by UVLabs** [comment]
testing this out but getting an api error, I think it's because my app is not yet reviewed, I just put it in the review process(might take a few days to get approved so testing can continue)
image

The plugin i use to do pinterest sharing doesn't actually use an app but the session cookie: http://valvepress.com/get-pinterest-session-cookie/ our way may be the more standard way but hopefully pinterest doesn't have strict processes like Facebook.

@contactashish13 were you able to test this using a development pinterest app?

**Comment by contactashish13** [comment]
@UVLabs I have tested and it works properly.

**Comment by selul** [comment]
@contactashish13 can we make the error message more explicit? Showing Array there is not to helpfull, you can use var export or json encode.

**Comment by UVLabs** [comment]
@contactashish13 how exactly did you test? I need to write documentation for connecting pinterest so I need to know if the I'm correct about the process, do you have an approved developer app? 

I submitted mine for review yesterday after I saw the error in the log

**Comment by contactashish13** [comment]
I didn't need an approved app. I tested with a newly created app. I created a Pinterest account by logging in with my Facebook account and then created an app. No review was required.

**Comment by UVLabs** [comment]
@contactashish13 Ok, I tested with a business Pinterest account, I'll test with a normal account to see, can you check my comment here when you're able to, waiting to merge it: https://github.com/Codeinwp/tweet-old-post/pull/196

**Comment by UVLabs** [comment]
strange, still getting the same error with an app created by a normal pinterest profile

**Comment by UVLabs** [comment]
I can't identify where in the share method "The pinterest service can not be used or was not found Error:" part of the error is being outputted to try to echo what exactly the error is, can you check it out?

I have attached my two versions of the plugin (both pulled from your respective pull requests)

[tweet-old-post-pro.zip](https://github.com/Codeinwp/tweet-old-post/files/2280654/tweet-old-post-pro.zip)
[tweet-old-post.zip](https://github.com/Codeinwp/tweet-old-post/files/2280655/tweet-old-post.zip)

**Pull request merged**
