### PR TITLE
Release 9.1

### PR DESCRIPTION
**Pull request by selul**

### CODE REVIEW

**Comment by rodica-andronache** [comment]
The Upgrade to pro button is no longer centered
Annotation on 2024-07-11 at 17-26-41

**Comment by selul** [comment]
@rodica-andronache fixed.

**Comment by rodica-andronache** [comment]
When using Revive Social  + Revive Social PRO ( without the license activated ) the link to enter your license from here, still points to the General page, not the new location 
Annotation on 2024-07-15 at 19-46-53

**Comment by Soare-Robert-Daniel** [comment]
> [!WARNING]
> If you test Webhook, change the Pro plugin dev build version to `3.1` or higher.

If you have a valid license, but your Pro plugin is not at least `3.1`, the button will remain locked, and on hover, a tooltip to upgrade the version is shown. 

Screenshot 2024-07-16 at 14 19 59

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel the link for the Purchase History here should be to store.themeisle.com
Annotation on 2024-07-16 at 18-12-15

**Pull request merged**
