### PR TITLE
Changes in add account buttons

### PR DESCRIPTION
**Pull request by contactashish13**
#478

### CODE REVIEW

**Comment by UVLabs** [comment]
@contactashish13 It doesn't seem like you've actually added the collapsing in this pull?

**Comment by contactashish13** [comment]
No, this only has the button tooltips. I will add the collapse next week to the same PR.

**Comment by contactashish13** [comment]
@UVLabs I've added the button. Can you please test?

**Comment by UVLabs** [comment]
@contactashish13 the button shows up before I even added an account: 

image

The button should not collapse the rest of the account buttons until 2 different networks are connected

**Comment by contactashish13** [comment]
@UVLabs this should be okay now.

**Pull request merged**
