### PR TITLE
#255

### PR DESCRIPTION
**Pull request by UVLabs**

### CODE REVIEW

**Comment by UVLabs** [comment]
@contactashish13 I fixed the conflict for here: https://github.com/Codeinwp/tweet-old-post/pull/364

Can you please take a look when you have some time? It seems like the cron code is not always triggering

**Comment by contactashish13** [comment]
@UVLabs sure. Is this for the publish now feature or for the scheduled posting? if you could list down the steps, it would make it easier to get to the root of the problem

**Comment by UVLabs** [comment]
@contactashish13 the issue here is that for some reason the publish now cron method is not working in Gutenberg. I used WP Control plugin to check the cron events on the site.

When you try to use the publish now feature in Classic Editor the cron event is triggered: 

image

But when you use it in Gutenberg it's not. 

This is one of the methods @HardeepAsrani created for Gut: 

https://github.com/Codeinwp/tweet-old-post/blob/59480b4ea9f2b86a2e87d3cac0c407b1efcaabad/includes/admin/class-rop-admin.php#L329

I tried registering the return of `wp_schedule_single_event` in the `publish_now` method and it returns true for Gutenberg so I'm not sure what's happening

**Comment by contactashish13** [comment]
@UVLabs I think the problem was that the action `rop_cron_job_publish_now` was not being triggered. I guess this is because this is a REST call and does not trigger the admin stuff. The action needs to be registered manually `add_action( 'rop_cron_job_publish_now', array( $this, 'rop_cron_job_publish_now' ) );` just before the method `update_rop_post_meta` returns.

image

I also found a UX bug that you may want to fix: in the classic editor, clicking on the label "Share immediately via Revive Old Posts" does not click the checkbox. I have to click on the checkbox for it to check.

**Comment by UVLabs** [comment]
@contactashish13 thank you for this, i'll test it out

**Comment by UVLabs** [comment]
@contactashish13 unfortunately that doesn't seem to have helped, did it work for you? the code seems to be getting inside the `publish_now` method but for some reason the schedule event is not being created

**Comment by contactashish13** [comment]
@UVLabs it worked for me. It created the non-repeating method and it even posted on twitter.

**Comment by UVLabs** [comment]
@contactashish13 I went back to test it one more time and it seem to have worked but only once and didn't work after that for either posting new post or updating previous ones, here's the commit with the added action: https://github.com/Codeinwp/tweet-old-post/pull/391/commits/aeb32b7aacf109afe33955e548ae0fef0aaf6b64

Did you do anything else?

@purplecodes @HardeepAsrani can you help test this out? I have attached a zip file with the change added 
[tweet-old-post.zip](https://github.com/Codeinwp/tweet-old-post/files/3438448/tweet-old-post.zip)

This has always been the case the feature doesn't seem to work reliably

**Comment by UVLabs** [comment]
@purplecodes @HardeepAsrani any update here?

**Comment by HardeepAsrani** [comment]
@contactashish13 I tried your advice and a lot of things on the internet and I'm not able to get it to work. :( Can you take a look and see if it works?

**Comment by contactashish13** [comment]
@UVLabs  I tried it again at my end and the behavior is pretty consistent. Do you want to deploy this on a public instance where I can debug?

**Comment by UVLabs** [comment]
@contactashish13 I created an online instance and tested it out. It does work, but it seems inconsistent and would work 3/5 times, I installed WP Control so you can use it to see quickly if the cron event gets scheduled.

Url: https://damp-pike.jurassic.ninja
username: demo
password: a6cEKGApDSKn

I'll keep testing it. I tried both methods:

- Sharing when adding a brand new post
- Sharing when updating an old post

**Comment by contactashish13** [comment]
@UVLabs I've changed the code a bit. Instead of calling
`add_action( 'rop_cron_job_publish_now', array( $this, 'rop_cron_job_publish_now' ) );`
I'm now calling
`$this->rop_cron_job_publish_now();` directly

It seems to work but throws these errors:

image

Also, from a UX point of view if I click the share immediately checkbox, the Update post button does not get enabled. I have to change some other element also to enable the button. @HardeepAsrani can you take a look?

**Comment by UVLabs** [comment]
@contactashish13 that seem to work well for updating posts but when creating new posts it doesn't seem to work 

@HardeepAsrani 
@purplecodes 

Can you guys test with the zip I attached? It has the code change which Ash mentioned. Try seeing if the post gets shared when creating a brand new post using "Add New" vs when updating an existing post
[tweet-old-post.zip](https://github.com/Codeinwp/tweet-old-post/files/3494891/tweet-old-post.zip)

**Comment by HardeepAsrani** [comment]
@contactashish13 This is publishing everything, even if I don't mark the post to be published then it publishes the draft of that post. @UVLabs

**Comment by contactashish13** [comment]
@HardeepAsrani @UVLabs then we just need to add a post status condition but do the changes fix the original problem?

**Comment by UVLabs** [comment]
@contactashish13 I want to get this into v8.5.0, since we're having trouble with Gutenberg; lets change this up a bit. Rather than latching onto the post attributes area of the edit screen, lets turn this feature into a metabox so that the user can make network selection within that metabox. Give it a `context` of `side` and `priority` of `high`

The metabox will be visible in the classic editor and should also work in Gutenberg(of course test).

**Comment by UVLabs** [comment]
@contactashish13 do you think you'd be able to get to this within the next week or 2?

**Comment by contactashish13** [comment]
@HardeepAsrani does Gutenberg support meta boxes as @UVLabs suggest? I'm not sure it does.

**Comment by UVLabs** [comment]
@contactashish13 Yes it does, we use a metabox for the share variations feature:

Classic Editor: https://prnt.sc/pptccn
Gutenberg: https://prnt.sc/pptdoz

Here's an example of a metabox that was added to the side with a high priority:

Classic Editor: https://prnt.sc/pptcmz
Gutenberg: https://prnt.sc/pptdx3

So leave this pull as it is, I'll archive it. Pull a copy of the v850 branch and do the changes there and submit as a separate pull request.

We're keeping the same operation as before except placing the checkbox inside a metabox

**Comment by HardeepAsrani** [comment]
Yea, you can do that but not sure how long that feature will last. Can't we find someway to trigger that? The reason it doesn't get triggered is that the request is going thru REST API so maybe @contactashish13 why that doesn't trigger it?

**Comment by contactashish13** [comment]
@UVLabs I agree with @HardeepAsrani that we should not depend on this feature continuing. We should focus on why its not happening. The endpoint triggers for me as I've shown in the past. It triggers for @UVLabs as well sometimes. So we need to find out why that "sometimes" occurs, which is something that only @UVLabs or you will be able to debug because it always triggers for me.

**Comment by UVLabs** [comment]
@contactashish13 this has been in the pipeline long enough. We have users holding on the feature for months and we haven't had the leeway to debug, test and implement it so we can't keep going back and forth as this is a feature which we will be tooting in v8.5.0 with the readme revamp.

At this point the best way forward is to move the feature over to a metabox which we can ship in the next version.

So let's turn this into a Metabox and archive this current implementation for now, we will continue looking into the best possible ways to get this to work for Gutenberg but for now the fact is that metaboxes work and are being used for similar features inside the Editor

**Comment by UVLabs** [comment]
Archiving this pull for now. I have assigned the metabox task: https://github.com/Codeinwp/tweet-old-post/issues/504 to myself and we will look into this native Gutenberg behaviour after 8.5.0 

Thank you guys for your work so far on this!

**Pull request merged**
