### PR TITLE
Twitter App Auth

### PR DESCRIPTION
**Pull request by mihaiiro**
Contains the code required for "Sign in with Twitter" functionality.

### CODE REVIEW

**Comment by UVLabs** [comment]
@mihaiiro can you try pulling the latest changes from master branch? There are some changes we made recently that your pull is trying to add back

**Comment by mihaiiro** [comment]
Hello @UVLabs 

Message received, working on it :)

**Comment by mihaiiro** [comment]
Removed the "extra" code and did the pull request again

**Comment by UVLabs** [comment]
@mihaiiro you removed some of the good code which you previously added:

https://github.com/Codeinwp/tweet-old-post/pull/411/commits/e2a6666c792d3f0798f7940eb52837a34d304ba4#diff-ca3b2be3ba57ebeb8563279663151bb6L215

https://github.com/Codeinwp/tweet-old-post/pull/411/commits/e2a6666c792d3f0798f7940eb52837a34d304ba4#diff-ca3b2be3ba57ebeb8563279663151bb6L226

https://github.com/Codeinwp/tweet-old-post/pull/411/commits/e2a6666c792d3f0798f7940eb52837a34d304ba4#diff-fbfdf2cba2fad46ffd4932c206d08493L514-L528

Can you undo your most recent commit? There are a few other lines like that

Here is the commit I was talking about which your original pull request was trying to add the code back:

https://github.com/Codeinwp/tweet-old-post/pull/401/commits/0e2985d94c5c91d9d2394ac7896c6f3edd36f4ba

In your original pull it was trying to add some of the code back, there are a few more lines:

https://github.com/Codeinwp/tweet-old-post/pull/411/commits/230ef9b0bea940a9a177abe2fc5124764a2d374d#diff-ca3b2be3ba57ebeb8563279663151bb6R214

https://github.com/Codeinwp/tweet-old-post/pull/411/commits/230ef9b0bea940a9a177abe2fc5124764a2d374d#diff-ca3b2be3ba57ebeb8563279663151bb6R225

---

Did pulling the latest changes from the master branch not sync your fork?

**Comment by UVLabs** [comment]
@mihaiiro to fix the travis error please add this line `dist: trusty` to the `travis.yml` : https://github.com/Codeinwp/tweet-old-post/pull/412/commits/485df391fda9a1c6785d709ec6b1e50883d9006d#diff-354f30a63fb0907d4ad57269548329e3R62

**Comment by UVLabs** [comment]
Im going to merge and then remove the pieces of code which shouldn't be there anymore

**Pull request merged**
