### PR TITLE
fix: move the license field to dashboard

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
## Summary

Moved the license to the dashboard page.

#### Free User

image

#### Activated

image

#### On Error

image

## Testing

Check if you can activate/deactivate the license.

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel tested this and have two questions:

1. is if it's normal for the license key area to show up in the free version? I didn't see this mention in the issue and I find it really weird. 
Screenshot on 2024-07-11 at 15-54-00

2. For tablets, I see that we are hiding the sidebar, or it's just not visible. In this case, the license key will also be hidden, and not accesibile to users. Not sure what the best approach would be here 
Screenshot on 2024-07-11 at 16-02-39

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel should I check here? Or are you still working on it? Thanks

**Comment by Soare-Robert-Daniel** [comment]
@rodica-andronache, you can wait. The free user problem is solved, but we need to see a good solution for the design of the sidebar in the tablet view.

**Comment by selul** [comment]
@Soare-Robert-Daniel we can add it under the publish button

**Comment by stefan-cotitosu** [comment]
The **here** link in the license key notice still points to Settings -> General instead of the ROP Dashboard page.

license-link-notice

**Comment by stefan-cotitosu** [comment]
@Soare-Robert-Daniel, I tested on tastewp and I don't see the license key field.

The build for the free version so from this PR, and the pro version is the live one (from customer's area).

Instance details:
https://pinpointhelp.s3-tastewp.com/wp-admin/
stefancoti
JwIep3kE0J0

**Comment by stefan-cotitosu** [comment]
It's working on my website, and on Tastewp it seems to be a cache issue. So let's clarify the design on Tablet and we are good to go here.

@JohnPixle, can you please suggest a format for displaying the sidebar on Tablet, which can be full-width or limited?

Screenshot 2024-07-11 at 16 47 59
Screenshot 2024-07-11 at 16 45 00

**Comment by Soare-Robert-Daniel** [comment]
This is how it looks:


https://github.com/user-attachments/assets/1ae5bf8a-1bf1-4203-9ed2-4b2e88769875

**Pull request merged**
